# Generated by Django 5.2.5 on 2025-10-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weborg', '0002_alter_category_options_alter_priority_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_content',
            field=models.CharField(max_length=150, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weborg.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='sub_parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weborg.task', verbose_name='Parent Task'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='sub_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='sub_title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weborg.category', verbose_name='Task Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weborg.priority', verbose_name='Task Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
